version: '2'
services:
  mysql:
        build: ./mysql
        ports:
        - 3306:3306
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
        - MYSQL_DATABASE=user_service
