apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    run: cluster-service-1
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: user-service-deploy
spec:
  replicas: 2
  template:
    metadata:
      name: user-service
      labels:
        run: cluster-service-1
    spec:
      containers:
        - name: user-container
          image: kimtaesoo/user-service:latest
          ports:
            - containerPort: 8090
