apiVersion: v1
kind: Service
metadata:
  name: user-mysql
  labels:
    app: user-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: user-mysql
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mysql-pvc
  labels:
    app: user-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: user-mysql-deploy
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-mysql
        tier: mysql
    spec:
      containers:
        - name: user-mysql-container
          image: kimtaesoo/user-service:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: test
            - name: MYSQL_PASSWORD
              value: test
            - name: MYSQL_DATABASE
              value: user_service
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: user-mysql-pvc
