kind: PersistentVolume
apiVersion: v1

metadata:
  name: local-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/pv-1
