spring:
  datasource:
      url: jdbc:mysql://user-mysql/user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: test
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
      max-active: 10
      max-idle: 5
      min-idle: 1
      initial-size: 5
      time-between-eviction-runs-millis: 5000
      min-evictable-idle-time-millis: 60000
      initialize: true
  jpa:
      show-sql: true
  #      Flyway DB 를 사용하여 데이터 초기화를 위하여 주석
      database: mysql
      hibernate.ddl-auto: create-drop